### ISSUE TITLE
Webpack 5 SideEffectsFlagPlugin fails in production mode

### ISSUE THREAD

**Issue by Enase** [mrsteele/dotenv-webpack#275]
In some reason I get the Type error in production mode only.

```
TypeError: dep.getModuleEvaluationSideEffectsState is not a function
    at NormalModule.getSideEffectsConnectionState (/{some_path}/node_modules/webpack-cli/node_modules/webpack/lib/NormalModule.js:879:23)
    at HarmonyImportSideEffectDependency.getModuleEvaluationSideEffectsState (/{some_path}/node_modules/webpack-cli/node_modules/webpack/lib/dependencies/HarmonyImportSideEffectDependency.js:50:20)
    at NormalModule.getSideEffectsConnectionState (/{some_path}/node_modules/webpack-cli/node_modules/webpack/lib/NormalModule.js:879:23)
    at /{some_path}/node_modules/webpack-cli/node_modules/webpack/lib/optimize/SideEffectsFlagPlugin.js:229:18
    at Hook.eval [as call] (eval at create (/{some_path}/node_modules/webpack-cli/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:10:16)
    at Hook.CALL_DELEGATE [as _call] (/{some_path}/node_modules/webpack-cli/node_modules/tapable/lib/Hook.js:14:14)
```

console.log of `dep` variable in my case:

```
ConstDependency {
  module: null,
  weak: false,
  optional: false,
  loc: SourceLocation {
    start: Position { line: 16, column: 25 },
    end: Position { line: 16, column: 36 }
  },
  expression: '{}',
  range: [ 594, 605 ],
  requireWebpackRequire: false
}
```

webpack config
```
const dotenv = require('dotenv');
const path = require('path');
const Dotenv = require('dotenv-webpack');
const pkg = require('../package.json');

const mode = process.env.WEBPACK_ENV || 'development';
const libraryName = pkg.name;

const envFile = path.join(__dirname, mode === 'production' ? '.env.prod' : '.env.dev');

module.exports = {
  mode,
  entry: {
    loader: path.join(__dirname, 'src', 'loader.js'),
  },
  devtool: mode === 'production' ? 'source-map' : 'inline-source-map',
  output: {
    library: libraryName,
    libraryTarget: 'umd',
    filename: `[name]${mode === 'production' ? '.min' : ''}.js`,
    path: path.join(__dirname, 'dist'),
    umdNamedDefine: true,
    globalObject: "typeof self !== 'undefined' ? self : this",
  },
  optimization: {
    minimize: mode === 'production',
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /(node_modules|bower_components)/,
      },
      {
        test: /\.(html|css|txt)$/,
        use: 'raw-loader',
      },
    ],
  },
  plugins: [
    new Dotenv({
      defaults: path.join(__dirname, '.env.defaults'),
      path: envFile,
      systemvars: true,
      safe: path.resolve(__dirname, '.env.example'),
      silent: false,
    }),
  ],
};
```

If I set it off - everything works fine
```
  optimization: {
    minimize: mode === 'production',
    sideEffects: false
  },
```

**Comment by mrsteele** [comment]
@Enase Taking off this plugin resolves that bug?

**Comment by Enase** [comment]
yes it is

**Comment by mrsteele** [comment]
you also removed `sideEffects`, did that make a difference turning on and off? I don't see this report from anyone else. Also, you included `dotenv` which is not needed in your require above.

**Comment by Enase** [comment]
@mrsteele I'll try to provide more details or example repo.
