### ISSUE TITLE
[LOG] process.env <object> {}

### ISSUE THREAD

**Issue by thisVioletHydra** [mrsteele/dotenv-webpack#280]
```

node 15
 "dotenv-webpack": "^5.1.0",
 "webpack": "5.6.0",
    "webpack-cli": "4.2.0",
```

dotenv - on 
![image](https://user-images.githubusercontent.com/11839238/99892381-69aab600-2c85-11eb-9df3-49acbde6f530.png)

dotenv - off
![image](https://user-images.githubusercontent.com/11839238/99892399-88a94800-2c85-11eb-9673-6ac8f70b8610.png)

HELP!

**Comment by thisVioletHydra** [comment]
and bonus 
```
[ERROR] 06:22:05 SyntaxError: Invalid left-hand side in assignment
[INFO] 06:23:03 Restarting: C:\FRONTEND\www\group-dashboard\group-dashboard-postman\dist\main.js has been modified
C:\FRONTEND\www\group-dashboard\group-dashboard-postman\dist\main.js:803
        {}.NODE_TLS_REJECT_UNAUTHORIZED = '0';
          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (node:internal/modules/cjs/loader:1018:16)
    at Module._compile (node:internal/modules/cjs/loader:1066:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Object.nodeDevHook [as .js] (C:\FRONTEND\www\group-dashboard\group-dashboard-postman\node_modules\node-dev\lib\hook.js:60:7)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\FRONTEND\www\group-dashboard\group-dashboard-postman\node_modules\node-dev\lib\wrap.js:76:3)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
[ERROR] 06:23:03 SyntaxError: Unexpected token '.'
```

**Comment by thisVioletHydra** [comment]
@mrsteele alarm! ;c

**Comment by mrsteele** [comment]
This is a copy of #271. Lets keep the conversation going over there.
