### ISSUE TITLE
v7 doesn't work with webpack 4

### ISSUE THREAD

**Issue by valyagolev** [mrsteele/dotenv-webpack#369]
v7 (both 7.0.0 and 7.0.1) fails with webpack 4 (after #360 I think), but the package.json claims to support that as a peer.

```
✖ ERROR TypeError: Cannot read property 'version' of undefined
    at Dotenv.apply (test-project/node_modules/dotenv-webpack/dist/index.js:65:38)
    at webpack (test-project/node_modules/webpack/lib/webpack.js:51:13)
    at devBuild (test-project/node_modules/preact-cli/lib/lib/webpack/run-webpack.js:23:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

v6.0.4 works well with webpack 4

**Comment by mrsteele** [comment]
@valyagolev Can you try with `v7.0.2` (just released yesterday). That *should* fix it but please let me know if it doesnt.

**Comment by mrsteele** [comment]
@valyagolev Did `v7.0.2` work for you?

**Comment by karlomajer** [comment]
> @valyagolev Did `v7.0.2` work for you?

I had the same issue. v7.0.2 fixed it, thanks!
