### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by lucasbento** [mrsteele/dotenv-webpack#8]
When using 1.1.0, the project throws this error:

```bash
> node server.js

module.js:341
    throw err;
    ^

Error: Cannot find module './src'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Project/node_modules/dotenv-webpack/index.js:9:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)```

**Comment by mrsteele** [comment]
nuts I see that... one sec...

**Comment by mrsteele** [comment]
Thanks for catching this. I updated the build now all the way to `v1.2.0` which has all features, tests, and build issues worked out.

I tested pulling that down locally from npm and I am not seeing any issues.

Thanks for all your help along the way with this. Hopefully solves all issues you were encountering.

Let me know if you got any other good ideas ;)
